### ISSUE TITLE
Drawable alignment with MaterialAboutActionItem onClickListener

### ISSUE THREAD

**Issue by daniel-stoneuk** [daniel-stoneuk/material-about-library#1]
Reported by reddit user.

Setting an event listener to the card makes the drawable lose alignment with the title of the card

Visible on emulator API level 16, however is not visible on any real device running API 25.

**Comment by lcsphantom** [comment]
I am the reddit user.

Sample code being used:

        MaterialAboutCard.Builder appCardBuilder = new MaterialAboutCard.Builder();
        appCardBuilder.addItem(new MaterialAboutTitleItem.Builder()
                .text("Some title.")
                .icon(R.drawable.ic_date_range_black)
                .build());

        appCardBuilder.addItem(new MaterialAboutActionItem.Builder()
                .text("Version")
                .subText("0.8.5")
                .icon(R.drawable.ic_info_black)
                .setOnClickListener(new MaterialAboutActionItem.OnClickListener() {
                    @Override
                    public void onClick() {
                        //Do something
                    }
                })
                .build());

        appCardBuilder.addItem(new MaterialAboutActionItem.Builder()
                .text("Licenses")
                .icon(R.drawable.ic_insert_drive_file_black)
                .build());

                return new MaterialAboutList.Builder().addCard(appCardBuilder.build()).build();


As mentioned before:
compileSdkVersion 25
minSdkVersion 16 
targetSdkVersion 25

Api Level 25

![screenshot from 2016-12-28 09-19-11](https://cloud.githubusercontent.com/assets/23656409/21520830/c5c1bc8c-ccde-11e6-8093-cca4992f9d05.png)

Api Level 16

![screenshot from 2016-12-28 09-18-48](https://cloud.githubusercontent.com/assets/23656409/21520828/c048cc3c-ccde-11e6-84c9-adb28eea3cae.png)

Let me know if you need me to provide anything else.

**Comment by daniel-stoneuk** [comment]
This was an interesting issue - it seems like there is a bug in the framework when setting background resources below API level 21. Fixed.
