### ISSUE TITLE
Remove item icon

### ISSUE THREAD

**Issue by cioraneanu** [daniel-stoneuk/material-about-library#11]
Really awesome library! My only request is if it's possible to have a method in MaterialAboutActionItem.Builder that removes the icon and it's empty space. I want to create cards with just the title and some long descriptions. Thank you for your work :)

**Comment by daniel-stoneuk** [comment]
Added! Don't really want to create a brand new release for this small feature, so for now you can replace the dependency with this:
```gradle
compile 'com.github.daniel-stoneuk:material-about-library:d0c69db1eb'
```
Thanks for using the library!

**Comment by daniel-stoneuk** [comment]
Should probably point out how to use it... Simply call `.shouldShowIcon(false)` on the `MaterialAboutActionItem.Builder()`

Just fixed a small bug, use this commit:
```gradle
compile 'com.github.daniel-stoneuk:material-about-library:3a10f88c76'
```

**Comment by cioraneanu** [comment]
Tested. Working great. Thank you for the fast action 👍
