### ISSUE TITLE
Subtitle with more lines possible? 

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#13]
I need about 7 rows. Even formatted, like url, email, address

**Comment by daniel-stoneuk** [comment]
Sure. Guessing you'd want some sort of HTML formatting to go with it? I'll
have it done by tonight.

**Comment by Rainer-Lang** [comment]
This would be really awesome! Thanks.

**Comment by daniel-stoneuk** [comment]
Use `MaterialAboutActionItem.Builder().subTextHtml(String subTextHtml)` like so: (`<br />` is line break)
```java
.subTextHtml("This is <b>HTML</b> formatted <i>text</i> <br /> It is very cool!")
```

**Comment by Rainer-Lang** [comment]
Thanks.
