### ISSUE TITLE
ConvenienceBuilder::createVersionActionItem -> without versionCode

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#15]
I would like to have the version info without versionCode.
I could provide a method (PR): 

- new method like "createVersionActionItemWithoutVersionCode"
or
- old method with added parameter like "boolean includeVersionCode"

Would do you prefer - and do you support this?

**Comment by daniel-stoneuk** [comment]
Old method with parameter for sure! I just got home so will be able to make
the change myself if that's easier

>

**Comment by Rainer-Lang** [comment]
It's up to you - what you prefer. :)
I'm just starting to work with your lib....sorry for the many questions.

**Comment by daniel-stoneuk** [comment]
Don't worry about the questions - you're giving me great ideas. I appreciate it!
