### ISSUE TITLE
ConvenienceBuilder: email item

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#17]
For me not really working. Opens selection for "copy to clipboard"...and much more

I suggest a solution with Intent.ACTION_SENDTO
https://developer.android.com/guide/components/intents-common.html#Email

...but I didn't test it.

**Comment by daniel-stoneuk** [comment]
Cheers for the heads up - copied it in from a pull request and didn't really test any of them. Tested and working now.
