### ISSUE TITLE
ConvenienceBuilder: WebViewDialog item -> horizontal scrollable

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#18]
I create a WebViewDialog item and use an url. The opened dialog is horizontal scrollable - on my Nexus5 about 0.5cm
This shouldn't happen.

**Comment by Rainer-Lang** [comment]
And please even "createWebViewDialogItem" with and without subtext. :)
And thanks a lot for the changes.

**Comment by daniel-stoneuk** [comment]
Ah about the `createWebViewDialogItem` with and without subText: I probably haven't made this clear enough but you are able to specify null as the subText parameter for no subText to appear. (Hence the `@Nullable` annotation.

**Comment by Rainer-Lang** [comment]
With "null" - now I know it. ;)
Yes sideways scrollable.

**Comment by Rainer-Lang** [comment]
btw with AboutLibraries this doesn't happen - if this helps.

**Comment by daniel-stoneuk** [comment]
Do you think you should be able to zoom it?

**Comment by daniel-stoneuk** [comment]
Alright so that's sorted. Anything else you want me to add before I create a release for the changes?  😂

**Comment by Rainer-Lang** [comment]
AAAHHHHH wait....this and this and that and also here this :-D

**Comment by daniel-stoneuk** [comment]
I'll take that as a no? 😝😂 

Thanks for all your suggestions. I have a habit of releasing things and not testing them - should probably stop doing that.

**Comment by Rainer-Lang** [comment]
Releasing without testing ... then I'll test it. ;)
