### ISSUE TITLE
Suggestion for example "licenses": use AboutLibraries 

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#19]
For the third party licenses I'm using the AboutLibraries of @mikepenz: https://github.com/mikepenz/AboutLibraries

**Comment by daniel-stoneuk** [comment]
Yep. I'm also using that in my personal app however I would like to avoid including external libraries with my library - hence I'm not bundling Android-Iconics with the library, it's only used in the Demo app.

I'll make it a "tip" in the README.md
