### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by DesigningKnights** [daniel-stoneuk/material-about-library#2]
Is there any way to make this work in a fragment instead of an activity?

**Comment by daniel-stoneuk** [comment]
Yep it's certainly possible - I'll get to work on it next week (away from PC).

**Comment by DesigningKnights** [comment]
Awesome. Thanks!

**Comment by smidaharoun** [comment]
Any updates about this issue?

**Comment by daniel-stoneuk** [comment]
Yep - I'm on my way home now, and should have some time to work on this
tonight. Should be a couple days at most.

Thanks for your patience!

**Comment by smidaharoun** [comment]
Good luck @daniel-stoneuk

**Comment by daniel-stoneuk** [comment]
Fragment support has been added to 1.3.0, will work on writing documentation soon but for now you can check out the demo or ask me 👍 . It's pretty similar to the activity.

**Comment by smidaharoun** [comment]
Thanks @daniel-stoneuk
