### ISSUE TITLE
How to show the back-arrow in the toolbar?

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#20]

**Comment by daniel-stoneuk** [comment]
Make sure your activity declaration looks something like this: 
```xml
<activity
            android:name=".ExampleMaterialAboutActivity"
            android:parentActivityName=".MainActivity"
            android:theme="@style/AppTheme.MaterialAboutActivity"
            tools:ignore="UnusedAttribute">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity" />
        </activity>
```

**Comment by Rainer-Lang** [comment]
I have different parent activites. I start the "about" put of the NavDrawer.

**Comment by daniel-stoneuk** [comment]
Do you use fragments with your NavDrawer?

**Comment by Rainer-Lang** [comment]
I'm using Activities and within Fragments (sometimes).

**Comment by daniel-stoneuk** [comment]
Oh right. Hmm, if you want to code your own logic for activity handling, you can check out [`MaterialAboutFragment`](https://github.com/daniel-stoneuk/material-about-library/blob/master/library/src/main/java/com/danielstone/materialaboutlibrary/MaterialAboutFragment.java) and see how I've done it in the demo app.

**Comment by Rainer-Lang** [comment]
Yes I think this is the only way.
