### ISSUE TITLE
Don't forget to upload the newest demo to Google Play ;)

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#21]

**Comment by daniel-stoneuk** [comment]
Doing that right now 👍

**Comment by daniel-stoneuk** [comment]
May I ask which app you're implementing this in?

**Comment by Rainer-Lang** [comment]
Will be launched hopefully in a few weeks. I'll tell it when it's available, ok? Till now, I couldn't tell it. I develop the app with partners.

**Comment by daniel-stoneuk** [comment]
That would be awesome, thanks - hope it goes well!
