### ISSUE TITLE
WebViewDialog just reacts strange.

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#22]
It's still sideways scrollable.
If I use a WebView in AboutLibraries - all is fine, nothin to scroll, all visible, even with margin around the content. I have to investigate this issue tomorrow.

**Comment by daniel-stoneuk** [comment]
Are you sure? Did you set the allowZooming parameter to false?

**Comment by Rainer-Lang** [comment]
Set to false. Then the whole page is visible - but a bit small.... ;)

**Comment by daniel-stoneuk** [comment]
Wait, so when it's set to false nothing will scroll which is what you want? and then you want to also be able to zoom in?

**Comment by Rainer-Lang** [comment]
In AboutLibs there is a margin/padding around the content - and the WebView is only vertical scrollable.
You could just test it.

**Comment by Rainer-Lang** [comment]
I don't need to zoom-in.

**Comment by daniel-stoneuk** [comment]
I'm really sorry I don't really have an idea of what you're looking for. Maybe a screenshot will help?

**Comment by Rainer-Lang** [comment]
I'll send ins tomorrow. Nö problem. ☺️

**Comment by Rainer-Lang** [comment]
SwiftKey is sometimes annoying....

**Comment by daniel-stoneuk** [comment]
Thanks, I might have a little break from the computer now!

**Comment by Rainer-Lang** [comment]
In AboutLibs I define on my own what should happen. Here is the code:
```
MaterialDialog.Builder alert = new MaterialDialog.Builder(ctx);

WebView webView = new WebView(ctx);
webView.getSettings().setJavaScriptEnabled(true);

webView.loadUrl(uri);

webView.setWebViewClient(new WebViewClient() {
  @Override
  public boolean shouldOverrideUrlLoading(WebView view, String url) {
    view.loadUrl(url);
    return true;
  }
  @Override
  public void onPageFinished(WebView view, String url) {
    view.loadUrl("javascript:document.body.style.margin=\"8%\"; void 0");
  }
});

alert.customView(webView, true)
    .negativeText(R.string.close)
    .onNegative((dialog, which) -> dialog.dismiss())
    .show();
```

I'm using Material-Dialogs. I'm sure you don't like to include this lib.
So I use the "normal" item and set my own ClickListener.

For me the issue is finished. Thanks for your effort.
