### ISSUE TITLE
add parameter that icon is always in the upper left corner

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#25]
I use the html text and the icon is vertically centered, which looks really "strange".
Please add a parameter to define if the icon should be vertically centered or in upper left corner.

**Comment by daniel-stoneuk** [comment]
I'll do that later today when I get the time, sorry for the wait.

**Comment by Rainer-Lang** [comment]
Don't be rushed. You're doing right. 👍 
These here are only suggestions, maybe you have another solution and we could discuss...

**Comment by daniel-stoneuk** [comment]
Use this dependency for now: 
```gradle
        compile 'com.github.daniel-stoneuk:material-about-library:b8d4ac6b9b'
```

**Comment by Rainer-Lang** [comment]
Will try it later or tomorrow.

**Comment by Rainer-Lang** [comment]
Tested: The icon seems a bit lower than the right action-title-text.

**Comment by daniel-stoneuk** [comment]
Could you post a screenshot? It looks to be fine here: ![screenshot](http://i.imgur.com/FwgvtRY.png)

**Comment by Rainer-Lang** [comment]
The html-icon IS not as high as the action title text - look at your screenshot.
BUT it could be that the icon has a "border" with transparent pixel - in the icon itself.

**Comment by daniel-stoneuk** [comment]
Oh right, I see what you mean. In my opinion that's a tiny detail and is probably in the icon itself so I wouldn't worry.

**Comment by Rainer-Lang** [comment]
Yes, like I wrote - could be the icon itself.
