### ISSUE TITLE
Customise size and color of text

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#26]
color/size:
- card title
- item title
- item subtext

**Comment by daniel-stoneuk** [comment]
I'm not sure whether this would be worth developing as the library is designed to follow material design guidelines.

**Comment by Rainer-Lang** [comment]
Please have a look here: https://material.io/guidelines/style/color.html#color-color-schemes
Text primary is 87% alpha, secondary is 54%. 
If you use a black then it's 87%->"de000000" and secondary 54%->"8a000000".

**Comment by daniel-stoneuk** [comment]
Don't think that size should really be customisable, if you are dead set on changing the text size then you can override individual layout files.
