### ISSUE TITLE
ConvenienceBuilder: Phone Action Item

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#27]

**Comment by mree58** [comment]
Until then, you can use this :)        

 authorCardBuilder.addItem(new MaterialAboutActionItem.Builder()
                    .text("Phone")
                    .subText("+90 850 840 95 21")
                    .icon(new IconicsDrawable(c)
                            .icon(GoogleMaterial.Icon.gmd_phone)
                            .color(ContextCompat.getColor(c, R.color.colorIcon))
                            .sizeDp(18))
                    .setOnClickListener(new MaterialAboutActionItem.OnClickListener() {
                        @Override
                        public void onClick() {
                            Intent intent = new Intent(Intent.ACTION_DIAL);
                            intent.setData(Uri.parse("tel:+90 850 840 95 21"));
                            c.startActivity(intent);
                        }
                    })
                    .build());

**Comment by Rainer-Lang** [comment]
Would you like to make a PR?

**Comment by daniel-stoneuk** [comment]
Thanks for the suggestion!
