### ISSUE TITLE
Disable sound effects on items that has no onClick action

### ISSUE THREAD

**Issue by Robyer** [daniel-stoneuk/material-about-library#28]
Currently on clicking any item (including the MaterialAboutTitleItem and MaterialAboutActionItem) it plays the system "click" sound, but it does't make sense for static items without any attached onClick action. 

Please disable sound effects on such items. In layout it can be done by using `android:soundEffectsEnabled="false"`, there will be similar method to do it programatically.

**Comment by daniel-stoneuk** [comment]
Sure. I'll work on this for 1.5.0 (hopefully tonight). Thanks!

**Comment by daniel-stoneuk** [comment]
Sorted. Thanks!
