### ISSUE TITLE
Feature: customization card style

### ISSUE THREAD

**Issue by Scrounger** [daniel-stoneuk/material-about-library#30]
@daniel-stoneuk:
Thanks for this great lib!
Can you please implement the option to customize the card layout (overriding dimens) and add the follwowing parameters to the card style:
```
        <item name="android:foreground">?attr/selectableItemBackground</item>
        <item name="cardCornerRadius">4dp</item>
        <item name="cardElevation">4dp</item>
        <item name="cardMaxElevation">4dp</item>
        <item name="cardPreventCornerOverlap">false</item>
        <item name="cardUseCompatPadding">true</item>
```

**Comment by daniel-stoneuk** [comment]
Of course - good point about the parameters to the card style. I'm not too sure but I think if you override any of [these layouts[(https://github.com/daniel-stoneuk/material-about-library/tree/master/library/src/main/res/layout) (by putting them in your app's layout folder) you should be able to change the dimensions - same with strings.

**Comment by daniel-stoneuk** [comment]
I've added the parameters, but made sure that they conform to material specs.

**Comment by Scrounger** [comment]
Perfect, thanks for fast implemnetation. Overriding the layout file is the better option, to get my standard card layout.

**Comment by daniel-stoneuk** [comment]
No problem! Just make sure there is corresponding views with the correct id's.

**Comment by Scrounger** [comment]
> No problem! Just make sure there is corresponding views with the correct id's.
Could cause a silent exception ;)
