### ISSUE TITLE
Feature: custom layout file for single MaterialAboutActionItem

### ISSUE THREAD

**Issue by Scrounger** [daniel-stoneuk/material-about-library#31]
@daniel-stoneuk:
Can you please implement the option to set a custom layout file for a single [MaterialAboutActionItem](https://github.com/daniel-stoneuk/material-about-library/blob/master/library/src/main/res/layout/mal_material_about_action_item.xml)

something like that:
**.layout(R.layout.myCustomMaterialAboutActionItem)**
```
        MaterialAboutCard.Builder licenseCardBuilder = new MaterialAboutCard.Builder();
        licenseCardBuilder.title(getString(R.string.licenses));

        licenseCardBuilder.addItem(new MaterialAboutActionItem.Builder()
                .text(getString(R.string.open_source_licenses))
                .icon(R.drawable.ic_about_licenses_24dp)
                .layout(R.layout.myCustomMaterialAboutActionItem)
                .setOnClickListener(new MaterialAboutActionItem.OnClickListener() {
                    @Override
                    public void onClick() {
                        Intent i = new Intent(c, OpenSourceLicenseActivity.class);
                        startActivity(i);
                    }
                })
                .build());
```

**Comment by daniel-stoneuk** [comment]
Sure. I won't create a new release for it just yet, but you can use the individual commit for now.

**Comment by daniel-stoneuk** [comment]
Ah. This isn't possible with the RecyclerView unless you create a custom MaterialAboutActionItem. I am instead working on creating a more modular system. Hang tight.

**Comment by daniel-stoneuk** [comment]
Spent quite a while on this. Creating a custom `MaterialAboutItem` (Extending MaterialAboutItem) & a custom `ViewTypeManager` (extending ViewTypeManager). Is the quickest way of doing it right now. Might look into easier support in the future. 

Can't guarantee stability in this build as I haven't properly tested if it even works. Cheers.

Use: 
```gradle
compile 'com.github.daniel-stoneuk:material-about-library:7f7bb3f922'
```

**Comment by Scrounger** [comment]
@daniel-stoneuk:
I played a bit around but didn't get it to work. Can you post an example please?

**Comment by daniel-stoneuk** [comment]
Sorry about that, I'll spend some time now creating a demo for it. Thanks.

**Comment by daniel-stoneuk** [comment]
Took quite a long time but it's fun! I've added custom items to the demo. You can try and figure out how it works if you'd like as I don't have the time to document it. 

Just quickly though, you need to:

1. Extend ViewTypeManager
2. Extend MaterialAboutItem ( see demo )
3. Return your ViewTypeManager in the activity or fragment

**Comment by Scrounger** [comment]
@daniel-stoneuk:
Great, now i understand the concept, thanks a lot!
