### ISSUE TITLE
Feature: MaterialAboutList Methode add

### ISSUE THREAD

**Issue by Scrounger** [daniel-stoneuk/material-about-library#32]
@daniel-stoneuk:
Because now, i would like to use your lib for diffrent thins like About, Changelog and licences, i nedd a method to dynamically add cards to MaterialAboutList.

Could you please implement a .add Method to MaterialAboutList or a Constructor that accepts a List<MaterialAboutCard>?

**Comment by daniel-stoneuk** [comment]
The MaterialAboutList contains a constructor that accepts a varargs list. I will add this functionality in the future, however for now you can pass in `cardArray.toArray(new MaterialAboutCard[cardArray.size()]).`

**Comment by Scrounger** [comment]
i have a json file with changelog for each version. For each version i would like to create a MaterialAboutCard. So i have to iterate throug the *.json file and create dynamically the MaterialAboutCards.

So using a MaterialAboutCard[] cardArray is the solution, thanks!

> MaterialAboutList.Builder() also has an .addCard() method which is what you're looking for?

really didn't get this to work. Can you please post a little example?

**Comment by daniel-stoneuk** [comment]
Check out the README:

"Return the list:


Create a MaterialAboutList using MaterialAboutList.Builder(), passing in the cards you would like to display.


        return new MaterialAboutList.Builder()
                .addCard(supportCardBuilder.build())
                .build();
    }
}"
