### ISSUE TITLE
Suggestion: ClickListener for MaterialAboutTitleItem

### ISSUE THREAD

**Issue by Rainer-Lang** [daniel-stoneuk/material-about-library#37]
I use the TitleItem for the app name. This item should be linked to Google Play.
May you add a ClickListener?

**Comment by daniel-stoneuk** [comment]
Added! You can use `ConvenienceBuilder.createRateOnClickAction()` to create a Play Store intent.

**Comment by Rainer-Lang** [comment]
I saw this RateActionItem. But it wasn't what I wanted right now. Maybe I will use it later.
Thanks for adding. 👍

**Comment by Rainer-Lang** [comment]
@daniel-stoneuk It isn't working. No onClick()

**Comment by daniel-stoneuk** [comment]
.setOnClickListener in the builder?

**Comment by Rainer-Lang** [comment]
In the builder of the TitleItem

**Comment by daniel-stoneuk** [comment]
There should be? Which dependency are you using. Also how's the app going?

**Comment by Rainer-Lang** [comment]
I set the Listener but no onClick()
