### ISSUE TITLE
Material keylines

### ISSUE THREAD

**Issue by HeinrichReimer** [daniel-stoneuk/material-about-library#4]
The library uses 16dp of card margin instead of 8dp which causes some alignment issues:

![screenshot_20161228-140944](https://cloud.githubusercontent.com/assets/5065698/21522663/f2eee8aa-cd07-11e6-9316-3f24c4d80e05.png)
*Card layout keylines*

![screenshot_20161228-141011](https://cloud.githubusercontent.com/assets/5065698/21522682/11befa5e-cd08-11e6-9ae9-192e3a6054ff.png)
*Standard keylines*

Both problems would be solved by using 8dp as card margin.
(16dp padding is perfectly fine)

**Comment by daniel-stoneuk** [comment]
Think this should be fixed now? Not too sure what the issue is exactly...

**Comment by HeinrichReimer** [comment]
Not yet fixed

**Comment by daniel-stoneuk** [comment]
Resolved. Thanks for the help!
