### ISSUE TITLE
Why INTERNET permission

### ISSUE THREAD

**Issue by olivierperez** [daniel-stoneuk/material-about-library#45]
Hi, first of all, thanks for the library ;-)

Can you explain me why you need the **android.permission.INTERNET** permission?
I didn't need it before, and I prefer not to need it.

**Comment by daniel-stoneuk** [comment]
I gathered that the internet permission wasn't something people mind about, as it was used in the Convenience Builder. I'll remove it and leave a note for people who need it. Thanks
