### ISSUE TITLE
Disable animation on start

### ISSUE THREAD

**Issue by rubengees** [daniel-stoneuk/material-about-library#47]
**Library version:** `1.8.2`
**AppCompat version:** `25.3.1`
 
When navigating to my `MaterialAboutFragment` subclass, it shows a short animation.
I do not have such animations for any other of my sections and thus it looks inconsistent.
Might it be possible to implement some kind of setting for disabling the animation?

**Comment by daniel-stoneuk** [comment]
Hi, I'll work on this soon. Thanks.

**Comment by daniel-stoneuk** [comment]
Sorry, been inundated with other work recently. I'm always up for pull requests, or you can fork the repo and easily remove the animation.
