### ISSUE TITLE
MinSDK15

### ISSUE THREAD

**Issue by easycheese** [daniel-stoneuk/material-about-library#5]
Is there a reason for this?  I'm currently using minSDK14 and don't really want to add flavors based on SDK int yet (my app is targeted towards older devices).

**Comment by daniel-stoneuk** [comment]
Nope there isn't a reason, however currently there might be a few issues
when setting OnClickHandlers on API <21. I'm planning to sort this out next
week and at the same time I will lower the minSDK to 14 (I didn't think
there were many devices on SDK 14 - 4.0 as many went straight to 4.0.4)

Maybe check back next Wednesday?

**Comment by daniel-stoneuk** [comment]
Lowered, check back soon for an update to the library

**Comment by easycheese** [comment]
Great thanks!
