### ISSUE TITLE
Black Background "Overlay" on Dark Theme

### ISSUE THREAD

**Issue by chrisonline** [daniel-stoneuk/material-about-library#58]
I get a dark "overlay" color with the black theme. It's all over the screen as you can see in the screenshot.
What's wrong here and how can I solve this? Any tips? What did I wrong?
The white theme works perfectly.

![about](https://cloud.githubusercontent.com/assets/2077218/26320852/c31da6fe-3f24-11e7-8f7d-f0f458a1072f.png)

**Comment by daniel-stoneuk** [comment]
May you please post your styles.xml?

**Comment by chrisonline** [comment]
Oh sorry forgot that:
Black Theme  

         
        <item name="mal_lightActionBar">false</item>
        <item name="mal_popupOverlay">@style/Theme.Mal.Light.PopupOverlay</item>
        <item name="mal_color_primary">@color/mal_text_primary</item>
        <item name="mal_color_secondary">@color/mal_text_secondary</item>


White Theme

		
		<item name="mal_lightActionBar">true</item>
		<item name="mal_popupOverlay">@style/Theme.Mal.Light.PopupOverlay</item>
		<item name="mal_color_primary">@color/mal_text_primary</item>
		<item name="mal_color_secondary">@color/mal_text_secondary</item>

**Comment by Robyer** [comment]
@chrisonline There is no "dark overlay" on your screenshots, you just set black color for the primary/secondary text, so it looks weird. Just remove these lines:

```
<item name="mal_color_primary">@color/mal_text_primary</item>
<item name="mal_color_secondary">@color/mal_text_secondary</item>
```
or set your own custom colors (depending on what you want to achieve).

**Comment by chrisonline** [comment]
@Robyer Oh my god. My mistake :-( Sorry to bother you about this...
