### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by kashifo** [daniel-stoneuk/material-about-library#59]
I think there should be an option to add copyright info, it'll be useful for commercial apps also open-source apps have copyright too.

**Comment by daniel-stoneuk** [comment]
By copyright do you mean library licenses or something else. You should be able to make it yourself in the meantime - that's the idea of the library.

**Comment by kashifo** [comment]
A copyright info like © 2017 Github Inc at the bottom of screen

**Comment by daniel-stoneuk** [comment]
You could easily put it under the app name so it looks like this: 

![screenshot_20170609-194851](https://user-images.githubusercontent.com/15860949/26990619-27f5d276-4d4f-11e7-8db4-0e9a151c2eb5.png)

```
appCardBuilder.addItem(new MaterialAboutTitleItem.Builder()
                .text("Material About Library")
                .desc("© 2017 Daniel Stone")
                .icon(R.mipmap.ic_launcher)
                .build());
```

**Comment by kashifo** [comment]
Okay then.
