### ISSUE TITLE
Issues with missing colorPrimary are back

### ISSUE THREAD

**Issue by rubengees** [daniel-stoneuk/material-about-library#60]
I just updated to `2.0.0` and I am seeing the issue with the incorrectly colored overscroll effect again:

![device-2017-06-10-142432](https://user-images.githubusercontent.com/8021265/27002722-af05d6a0-4de8-11e7-89f2-18e4c81d3319.png)

Before that i used the commit `faeb14f8ff` from JitPack, which worked fine.

Thanks in advance for having a look!

**Comment by daniel-stoneuk** [comment]
Hey, I reverted some of the theme changes because they broke the demo. What does it look like with the old commit?

**Comment by daniel-stoneuk** [comment]
Try the latest commit - getTheme now asks for a theme you have declared try that out (make sure the theme is extending Mal themes.

**Comment by rubengees** [comment]
You're right, the dark theme did not work, which I didn't notice before.
I was currently in the process of investigating whtat we could do, but you were faster :grin: 

Works perfectly. Thank you!
