### ISSUE TITLE
support library mismatch with project

### ISSUE THREAD

**Issue by DesigningKnights** [daniel-stoneuk/material-about-library#66]
Hi, the current android support libraries are at 26.0.1, causing Android Studio to refuse to compile with the current library, since it's at 25.3.1.

**Comment by daniel-stoneuk** [comment]
Hi, sorry about that. I'm currently away from my pc but feel free to make a pull request changing the dependencies and then use the commit in gradle. 

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DesigningKnights** [comment]
I made the pull request, and fixed the support library version, as well as added the repository for the google maven files.

**Comment by DesigningKnights** [comment]
Hi again, sorry, I don't know enough about jitpack, does it automatically rebuild for changes?  Even though the changes were merged, I'm still getting the same error about the mismatch when using the repository through jitpack.

**Comment by daniel-stoneuk** [comment]
Use the commit id
```
	dependencies {
	        compile 'com.github.daniel-stoneuk:material-about-library:b6d3ffe515'
	}

```


_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DesigningKnights** [comment]
Ah, thanks.

**Comment by daniel-stoneuk** [comment]
Check out version 2.2.3 which supports three different support library versions :) Thanks.
