### ISSUE TITLE
Memory Leak when using ConvenienceBuilder.createAppTitleItem()

### ISSUE THREAD

**Issue by code-schreiber** [daniel-stoneuk/material-about-library#74]
It seems when passing context to ConvenienceBuilder.createAppTitleItem() the activity instance is leaked.
###### Code to reproduce
```java
    @NonNull
    @Override
    protected MaterialAboutList getMaterialAboutList(@NonNull Context context) {
        MaterialAboutCard card = new MaterialAboutCard.Builder()
                .addItem(ConvenienceBuilder.createAppTitleItem(context)) // This leaks the activity
                .build();
        
        return new MaterialAboutList.Builder()
                .addCard(card)
                .build();
    }
```
###### Leakcanary says
![screenshot_1518513424](https://user-images.githubusercontent.com/759086/36141996-11afc596-10a7-11e8-9991-da6be5c9e3db.png)

Now, from what I understand about it is this a [known leak ](https://github.com/square/leakcanary/blob/master/leakcanary-android/src/main/java/com/squareup/leakcanary/AndroidExcludedRefs.java#L241) and affects `JELLY_BEAN`up to `MARSHMALLOW`.

The way to easily avoid it in ConvenienceBuilder would be to pass the application context and not the activity directly.

**Comment by daniel-stoneuk** [comment]
Merged! Thank you.

**Comment by code-schreiber** [comment]
You are very welcome 😀
