### ISSUE TITLE
Change background color of a specific card

### ISSUE THREAD

**Issue by judemanutd** [daniel-stoneuk/material-about-library#76]
I have set the theme and everything is working fine, i would like to change the background color of a specific card rather than apply the customized theme color to all cards, how can i do that?

**Comment by daniel-stoneuk** [comment]
Hi, this is not currently possible with the library however I'll definitely implement that soon. I will be doing some work on the library in the next week and will add this functionality.

**Comment by judemanutd** [comment]
Thanks for the quick reply, looking forward to the new update.

**Comment by daniel-stoneuk** [comment]
Not solved yet, will work on soon.
