### ISSUE TITLE
Suggestion: Align title and non-title elements 

### ISSUE THREAD

**Issue by code-schreiber** [daniel-stoneuk/material-about-library#79]
One of the first things that I noticed when creating an about screen with a `MaterialAboutTitleItem` and a `MaterialAboutActionItem` is that the icon and text of the _title_ item are not aligned with the icon and text of the _action_ item.
A possible solution could be based on margins, after all, the title image should still be bigger than the other ones.

I tried to illustrate the issue with a screenshot where the blue lines belong to the title and the red ones to the action item.

![screenshot with grid](https://user-images.githubusercontent.com/759086/38364692-e939914a-38d9-11e8-8497-dc1cd0bcb202.png)

I am aware that this is not going to be an issue for everyone but I believe this change will make many eyes happy 👀

**Comment by daniel-stoneuk** [comment]
![screen shot 2018-04-06 at 14 35 06](https://user-images.githubusercontent.com/15860949/38424074-cdd68740-39a7-11e8-8836-103f8c4201b3.png)

You're right, I quite prefer the "new" design. Thanks.

I'll commit if you don't have any other design ideas.

**Comment by code-schreiber** [comment]
The "new" design looks very nice! 👍 

The only thing that I would consider changing is the spacing for the smaller icons, now it seems too big to left and right. I'm aware that the app icon is usually bigger and that influences the spacing of the whole screen, so my suggestion would be to reduce the spacing of both app and non-app icons.
Other than that thanks for this change!

Be aware that this is a breaking change in terms of design and it should be very clear for library consumers that their screens will potentially look a bit different after updating.

**Comment by daniel-stoneuk** [comment]
Yeah, I see what you mean. 

If we did decrease the spacing of both types of icon, I believe that the title icon will be too near the edge of the card. This is assuming we want the action icon to be centered with the title icon.

It does seem like material design is heading towards more whitespace and the extra spacing doesn't feel too out of place. It definitely looks better than the original.

Good point about breaking changes. I'll make that clear.

After testing however, it doesn't look that bad with reduced title padding:

![image](https://user-images.githubusercontent.com/15860949/38426547-d8ff2cf6-39ae-11e8-81ce-52a98bb0a62e.png)

**Comment by code-schreiber** [comment]
Nice 🎉
