### ISSUE TITLE
Override icon tint?

### ISSUE THREAD

**Issue by 19lmyers** [daniel-stoneuk/material-about-library#85]
I'm using this in a DayNight themed app, and I'm looking for a way to set my icon color to a different color depending on the theme, but this doesn't seem to support a way to override icon tints. Could you add something like a icon tint value?

**Comment by daniel-stoneuk** [comment]
Hi, the icon tint is determined by the drawable that you pass into the about list - if you're using a library for icons, you can do something similar to the demo.

**Comment by daniel-stoneuk** [comment]
Closed due to inactivity.
