### ISSUE TITLE
Add AndroidX support

### ISSUE THREAD

**Issue by systemallica** [daniel-stoneuk/material-about-library#87]
The release of the new [AndroidX ](https://android-developers.googleblog.com/2018/05/hello-world-androidx.html)packages is imminent, and this library cannot be used with AndroidX in its current state.

Given that all new development will be done in the AndroidX packages, I think that supporting it would be a good idea.

A refactoring guide can be found [here](https://developer.android.com/topic/libraries/support-library/refactor). I don't know if further modifications would be necessary.

**Comment by daniel-stoneuk** [comment]
Good point. I'll update the support library versions and add AndroidX support.

**Comment by daniel-stoneuk** [comment]
Do you know if it works yet with jetifier?

**Comment by systemallica** [comment]
Actually I'm not sure. I'm still using Android Studio 3.1.4

**Comment by eclectice** [comment]
> jetifier

The latest AndroidX should be OK

**_gradle.properties_**
```
android.useAndroidX = true
android.enableJetifier = false
```
**_build gradle_**
```
implementation "com.google.android.material:material:$material_version"
implementation "androidx.appcompat:appcompat:$legacy_support_v4_version"    
implementation "androidx.legacy:legacy-support-v4:$legacy_support_v4_version"
implementation "androidx.legacy:legacy-support-v13:$legacy_support_v4_version"
```

I really like to use your About library since there is a support for Licenses entry. But, I have just moved to AndroidX.

**Comment by eclectice** [comment]
OK, I try to refactor everything in your library codes to AndroidX but the example app uses LicenseAdapter from [GITHUB yshrsmz/LicenseAdapter](https://github.com/yshrsmz/LicenseAdapter) which currently doesn't support AndroidX.

**Comment by daniel-stoneuk** [comment]
Thanks for taking a look into it. The example using License adapter as an example actually isn't in the latest release, I'm wondering if supporting custom adapters is a good feature.

So you can confirm jetifier does not work with material about library? If this is the case, I'll probably create a new branch and support both support library and AndroidX versions separately. 

On another note, how many libraries have you encountered that don't play well with AndroidX, I'm looking to migrate soon.

**Comment by daniel-stoneuk** [comment]
Thanks. I would also like to add AndroidX support, however, I am more inclined to wait until AndroidX is more common because (correct me if I'm wrong) whilst a support library dep can be used with jetifier, an AndroidX dep can't be used in a support library project.

Would you agree here or do you think I should create two separate branches?

**Comment by eclectice** [comment]
Yes, I guess having two separate branches (Support Lib and AndroidX) is the
best solution at the moment until AndroidX becomes common...

**Comment by bernaferrari** [comment]
Released now! Keep in mind all future updates to support library will only happen in androidx.

**Comment by LithiumSR** [comment]
I tried using AndroidX but the MaterialAboutActivity doesn't provide any getResources() or startActivity(). getString etc
It was fine before I did the refactoring

**Comment by DerTyp7214** [comment]
i compiled by myself without testapp.
if someone need it with androidx: https://github.com/DerTyp7214/material-about-library/releases/tag/2.3.0

**Comment by eclectice** [comment]
I tried `implementation "com.github.daniel-stoneuk:material-about-library:2.3.0"` but I think the **MaterialAboutCard.customAdapter** is broken.

**Comment by daniel-stoneuk** [comment]
Hi guys, apologies for the delay.

Could you please test if 2.4.2 works?

Thanks

**Comment by DerTyp7214** [comment]
@daniel-stoneuk I will try when I'm back from work

**Comment by eclectice** [comment]
Tested this about-library release 2.4.2 (Androidx) with the customAdapter
support for my app. It works fine now with the LicenseAdapter version 2.2.2.

**Comment by daniel-stoneuk** [comment]
Brilliant! Hopefully support for @yshrsmz 's LicenseAdapter should make life a bit easier! @eclectice

**Comment by systemallica** [comment]
The new version is working great, thank you.
