### ISSUE TITLE
Making This Library Available to Developers Using Xamarin.Android

### ISSUE THREAD

**Issue by VaslD** [daniel-stoneuk/material-about-library#90]
I have made a private [Xamarin bindings project](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/) (like a port but way easier) for this library to make it available for an Android app written in C#.

Can I publish the Xamarin version to [NuGet.org](https://www.nuget.org/) and link it to this project? The package will then be publicly available. I'm also hoping that you can put the NuGet package link (once published) on ReadMe to help other developers find the C# version of your library.

**Comment by daniel-stoneuk** [comment]
Yes please that sounds great!

**Comment by VaslD** [comment]
Sorry for getting back to you so late.

Looks like someone already created a bindings project and published it on NuGet: [Karamunting.Android.MaterialAboutLibrary](https://www.nuget.org/packages/Karamunting.Android.MaterialAboutLibrary/). It was last updated last year so I'm not sure if they were still maintaining it.

I uploaded the updated version as well: [DanielStone.MaterialAboutLibrary.Xamarin](https://www.nuget.org/packages/DanielStone.MaterialAboutLibrary.Xamarin/). It (may) currently has some issues as AndroidX implementations are in very early stage on Xamarin side. I will update the bindings once Xamarin's Android Support Libs come out of pre-release.

**Comment by daniel-stoneuk** [comment]
@VaslD Brilliant, do you want to PR with a link to this in the README?
