### ISSUE TITLE
Remove CardView dependency in favour of MaterialCardView from Material Components

### ISSUE THREAD

**Issue by EdricChan03** [daniel-stoneuk/material-about-library#95]
Currently, the library uses the [`CardView`](https://developer.android.com/reference/androidx/cardview/widget/CardView?hl=en) widget from the `androidx.cardview` library. However, it seems that the library hasn't been maintained for a while.

A better alternative of the `CardView` widget would be the [`MaterialCardView`](https://developer.android.com/reference/com/google/android/material/card/MaterialCardView?hl=en) widget which is an improved version of the `CardView` widget but supports the latest Material Design specs. This also removes the required dependency of the `androidx.cardview` library, especially if users remove this library in favour of the `MaterialCardView` widget.

EDIT: Turns out there's a PR for this: #94

**Comment by daniel-stoneuk** [comment]
Merged the PR. Thanks. I need to make these updates as well for my other apps that are now using AndroidX but I haven't got much time right now.
