### ISSUE TITLE
Support for Material Components theming system/DayNight styles

### ISSUE THREAD

**Issue by EdricChan03** [daniel-stoneuk/material-about-library#96]
Currently, the library's `Theme.Mal.*` styles extend the former AppCompat themes. However, my project uses the new themes provided by the Material Components for Android library.

Will there be any support for this?

EDIT: The Material Components theming system also has support for DayNight styles which can be used for implementing a system-wide dark mode.

**Comment by daniel-stoneuk** [comment]
This should be supported by the library. I'll work on it.

**Comment by daniel-stoneuk** [comment]
Going to be resolved very soon by removing mal themes
